name: release

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Build
      run: npm run build
    - name: Upload bundles
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Pack
      env:
        AMO_KEY: ${{ secrets.AMO_KEY }}
        AMO_SECRET: ${{ secrets.AMO_SECRET }}
        CRX_PRIV_KEY: ${{ secrets.CRX_PRIV_KEY }}
        CWS_CLIENT_ID: ${{ secrets.CWS_CLIENT_ID }}
        CWS_CLIENT_SECRET: ${{ secrets.CWS_CLIENT_SECRET }}
        CWS_TOKEN: ${{ secrets.CWS_TOKEN }}
        MS_ACCESS_TOKEN_URL: ${{ secrets.MS_ACCESS_TOKEN_URL }}
        MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
        MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
        MS_PRODUCT_ID: ${{ secrets.MS_PRODUCT_ID }}
      run: npm run pack
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SERVER_TOKEN: ${{ secrets.SNAPSHOT_TOKEN }}
      run: npm run release